Revert 2c2777dc462e6385678a6e699fa04ffeea336371 -- breaks decode tests
The fix to #871 breaks decode unit tests, that is:

cargo test --release --features=decode_test

fails either with a segfault or an indefinite spin.  I got no useful error output, but TD gets:

error: failed to run custom build command for `rav1e v0.1.0 (/home/thomas/sandbox/xav1)`
process didn't exit successfully: `/home/thomas/sandbox/xav1/target/release/build/rav1e-50bde2c63e94b5ba/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)

Looks like a bug i new bindgen?